[package]
name = "dist-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
smol = "2.0.0"
stderrlog = "0.6.0"
uuid = { version = "1.10.0", features = ["fast-rng", "serde", "v4"] }
